MvcAuth/Models/ReportViewModels.cs
using System;
using System.ComponentModel.DataAnnotations;
using MyBlog.Entities;

namespace MvcAuth.Models
{
    public class ReportViewModel
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public int CommentId { get; set; }
        [DataType(DataType.MultilineText)]
        public string ReportDetail { get; set; }
        public DateTime ReportDate { get; set; }
    }
    public class ReportViewModelMapper
    {
        public Report MapFromModel(ReportViewModel reportModel)
        {
            return new Report
            {
                Id = reportModel.Id,
                CommentId = reportModel.CommentId,
                UserId = reportModel.UserId,
                UserName = reportModel.UserName,
                ReportDate = reportModel.ReportDate,
                ReportDetail = reportModel.ReportDetail,
            };
        }
        public ReportViewModel MapToModel(Report report)
        {
            return new ReportViewModel
            {
                Id = report.Id,
                CommentId = report.CommentId,
                UserId = report.UserId,
                UserName = report.UserName,
                ReportDate = report.ReportDate,
                ReportDetail = report.ReportDetail,
            };
        }


    }

}

MvcAuth/Controllers/CommentsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using MyBlog.Data.Service;
using MvcAuth.Models;
using MyBlog.Entities;


namespace MvcAuth.Controllers
{
    public class CommentsController : Controller
    {
        private readonly IServiceComment _commentService = null;
        public CommentsController(IServiceComment commentService)
        {
            _commentService = commentService;
        }

        // GET: CommentsModels
        public ActionResult Index()
        {
            var comments = _commentService.FindAll();
            List<CommentViewModel> list = new List<CommentViewModel>();
            foreach (var item in comments)
            {
                list.Add(Mapper.Map<Comment, CommentViewModel>(item));
            }
            return View(list);
        }

        // GET: CommentsModels/Details/5
        public ActionResult Details(int id)
        {

            var comment = _commentService.FindById(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(Mapper.Map<Comment,CommentViewModel>(comment));
        }

        // GET: CommentsModels/Edit/5
        [Authorize(Roles = "Administrator,User")]
        public ActionResult Edit(int id)
        {

            var comment = _commentService.FindById(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(Mapper.Map<Comment,CommentViewModel>(comment));
        }

        // POST: CommentsModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CommentViewModel commentViewModel)
        {
            if (ModelState.IsValid)
            {
                _commentService.Edit(Mapper.Map<CommentViewModel,Comment>(commentViewModel));
                return RedirectToAction("Index");
            }
            return View(commentViewModel);
        }

        // GET: CommentsModels/Delete/5
        [Authorize(Roles = "Administrator,User")]
        public ActionResult Delete(int id)
        {
            var comment = _commentService.FindById(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(Mapper.Map<Comment,CommentViewModel>(comment));
        }

        // POST: CommentsModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var comment = _commentService.FindById(id);
            _commentService.Delete(comment);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcAuth/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using AutoMapper;
using MvcAuth.Models;
using MyBlog.Data.Service;
using MyBlog.Entities;


namespace MvcAuth.Controllers
{
    public class ReportsController : Controller
    {
        private readonly IServiceReport _reportService = null;
        public ReportsController(IServiceReport reportService)
        {
            _reportService = reportService;
        }

        // GET: ReportsModels
        public ActionResult Index()
        {
            var reports = _reportService.FindAll().ToList();
            List<ReportViewModel> list = new List<ReportViewModel>();
            foreach (var item in reports)
            {
                list.Add(Mapper.Map<Report,ReportViewModel>(item));
            }
            return View(list);
        }

        // GET: ReportsModels/Details/5
        public ActionResult Details(int id)
        {
            var report= _reportService.FindById(id);

            if (report == null)
            {
                return HttpNotFound();
            }
            return View(Mapper.Map<Report,ReportViewModel>(report));

        }

        // GET: ReportsModels/Create

        public ActionResult Create(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        // POST: ReportsModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ReportViewModel reportViewModel, int id)
        {
            if (ModelState.IsValid)
            {
                reportViewModel.UserId = User.Identity.GetUserId();
                reportViewModel.ReportDate = DateTime.Now;
                reportViewModel.UserName = User.Identity.GetUserName();
                reportViewModel.CommentId = id;
                
                _reportService.Create(Mapper.Map<ReportViewModel,Report>(reportViewModel));
                return RedirectToAction("Index");
            }

            return View(reportViewModel);
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcAuth/Views/Reports/Create.cshtml
@model MvcAuth.Models.ReportViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>Report a complaint about comment:</h2>


@using (Html.BeginForm("Create", "Reports",
                       new { id = @ViewBag.id }, FormMethod.Post, null))
                    {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">

                        <hr />
                        <div class="form-group">
                            @Html.LabelFor(model => model.ReportDetail, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.ReportDetail, 5, 100, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ReportDetail, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>

                    @section Scripts {
                        @Scripts.Render("~/bundles/jqueryval")
                    }

MvcAuth/Views/Reports/Details.cshtml
@model MvcAuth.Models.ReportViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <p>
        @Html.ActionLink("Block This Comment", "Edit", "Comments",
                 new { id = Model.CommentId },
                 null)
    </p>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CommentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CommentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReportDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReportDetail)
        </dd>

    </dl>
</div>
<p>
 
    @Html.ActionLink("Back to List", "Index")
</p>

MvcAuth/Views/Reports/Index.cshtml
@model IEnumerable<MvcAuth.Models.ReportViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CommentId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReportDetail)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CommentId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReportDetail)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
        </td>
    </tr>
}

</table>