MvcAuth/Controllers/RolesController.cs
using System.Web.Mvc;
using MyBlog.Data.Service;
 
namespace MvcAuth.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class RolesController : Controller
    {
        private readonly IServiceUserRoles _userRolesService = null;

        public RolesController(IServiceUserRoles userRolesService)
        {
            _userRolesService = userRolesService;
        }

        
        public ActionResult Index()
        {
            var rolelist = _userRolesService.FindAll();
            ViewBag.Roles = rolelist;

            var userlist = _userRolesService.FindAllUsers();
            ViewBag.Users = userlist;

            ViewBag.Message = "";

            return View();
        }


        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }
          
        //
        // POST: /Roles/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {

            try
            {
                _userRolesService.Create(collection["RoleName"]);
                ViewBag.Message = "Role created successfully !";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(string roleId)
        {
            _userRolesService.Delete(roleId);
            return RedirectToAction("Index");
        }

        //
        // GET: /Roles/Edit/5
        public ActionResult Edit(string roleId)
        {
            var thisRole = _userRolesService.FindById(roleId);
            return View(thisRole);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Microsoft.AspNet.Identity.EntityFramework.IdentityRole role)
        {
          
            try
            {
                _userRolesService.Edit(role);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        //  Adding Roles to a user
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RoleAddToUser(string userId, string roleId)
        {
            _userRolesService.RoleAddToUser(userId, roleId);

            ViewBag.Message = "Role created successfully !";

            // Repopulate Dropdown Lists
            var rolelist = _userRolesService.FindAll();
            ViewBag.Roles = rolelist;
            var userlist = _userRolesService.FindAllUsers();
            ViewBag.Users = userlist;

            return View("Index");
        }


        //Getting a List of Roles for a User
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles(string userId)
        {
            if (!string.IsNullOrWhiteSpace(userId))
            {
                ViewBag.RolesForThisUser = _userRolesService.GetRoles(userId);
                // Repopulate Dropdown Lists
                var rolelist = _userRolesService.FindAll();
                ViewBag.Roles = rolelist;
                var userlist = _userRolesService.FindAllUsers();
                ViewBag.Users = userlist;
                ViewBag.Message = "Roles retrieved successfully !";
            }

            return View("Index");
        }

        //Deleting a User from A Role
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser(string userId, string roleId)
        {

            
            try
            {
                _userRolesService.DeleteRoleForUser(userId, roleId);
            }
            catch
            {
                ViewBag.Message = "This user doesn't belong to selected role.";
            }

            // Repopulate Dropdown Lists
            var rolelist = _userRolesService.FindAll();
            ViewBag.Roles = rolelist;
            var userlist = _userRolesService.FindAllUsers();
            ViewBag.Users = userlist;

            return View("Index");
        }

    }
}

MvcAuth/Views/Shared/CreateCommentView.cshtml
@model MvcAuth.Models.CommentViewModel

@using (Html.BeginForm("CreateComment", "Articles", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Add New Comment Here:</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <div class="col-md-10">
            @Html.EditorFor(model => model.CommentDetail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CommentDetail, "", new { @class = "text-danger" })
        </div>
    </div>
    @Html.HiddenFor(model => model.ArticleId, new { htmlAttributes = new { @class = "form-control" } })

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcAuth/Views/Shared/RankArticleView.cshtml
@using Microsoft.AspNet.Identity
<div class="panel-body">
    @using (Html.BeginForm("RankArticle", "Articles", new { id = @ViewBag.Id, userId = User.Identity.GetUserId()  }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <p>Rank this article!</p>
        <div class="row">
            <div class="col-1">
                @Html.DropDownList("Rank", (List<SelectListItem>)ViewBag.RankList, "Select ...")
            </div>
            <div class="col-11">
                <p><input type="submit" value="Rank" class="btn btn-sm btn-primary" /></p>
            </div>

        </div>
    }
</div> <!-- End Panel Body-->

MvcAuth/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MyBlog</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">

        <a class="navbar-brand" href="#">My Blog!</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Home", "Index", "Home", routeValues: null, htmlAttributes: new { @class = "nav-link" })
                    <span class="sr-only">(current)</span>
                </li>
                <li class="nav-item">
                    @Html.ActionLink("About", "About", "Home", routeValues: null, htmlAttributes: new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contact", "Contact", "Home", routeValues: null, htmlAttributes: new { @class = "nav-link" })
                </li>
                <li class="nav-item">@Html.ActionLink("Role Manager", "Index", "Roles",routeValues: null, htmlAttributes: new { @class = "nav-link" })</li>
            </ul>
            @Html.Partial("_LoginPartial")
            @*<form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>*@
        </div>

        @*<div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("MVC Blog", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>*@
    </nav>
    <div ><p></p>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>